---

- hosts: all
  become: true
  tasks:


  - name: install apache2 and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: remove vim-knox
    apt:
       name: vim-know
       state: absent
    when: ansible_distribution in ["Ubuntu","Debian"]


  - name: install apache2 and php packages
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in  ["Centos","Fedora"]

  - name: remove vim-knox
    yum:
       name: vim-know
       state: absent
    when: ansible_distribution in ["Centos","RedHat"]

